Issue 30 vk UI 2
DotaSirius/Dota2_Sirius pull request #100
Opened 2021-12-14 16:33 UTC by NickaKos11

2021-12-14 17:21 UTC, NickaKos11 commented
На реквест только UI

2021-12-15 07:04 UTC, just-evseev requested changes
Надо бы поправить все замечания отSwiftLint тоже

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Coordinator.swift
> +}
Не используется?

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Model/PlayerList.swift
> +    //let playerImage: UIImage
Вроде как договорились использовать URL для картинок, а потом компонента с картинками сама будет находить картинки

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    init(networkService: NetworkService) {
Архитектурно все еще странно что конвертер хранит ссылку на сервисы, надо уйти от этого. Зависимость должна быть обратной - сервис хранит ссылку на ковертер

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +        return MainMatchInfo(winnersLabelText: winnersLabelText, gameTimeLabelText: gameTimeLabelText, firstTeamScoreLabelText: firstTeamScoreLabelText, secondTeamScoreLabelText: secondTeamScoreLabel
Тут надо сделать красивые переносы, сейчас не читаемо

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +        }
А зачем эта логика? Кстати можно использовать let safeNumber: Int, ничего не поменяется

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +        return PlayerList(playerNameLabelText: playerNameLabelText, playerRankText: playerRankText, playerKillsText: playerKillsText, playerDeathsText: playerDeathsText, playerAssitsText: playerAssit
Нужны переносы строк

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +            return "-"
Точно так красиво будет? Может дефолтные значение сделать более осмысленные? Например тут Anonymous

Дальше тоже нужно поправить

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +    func getRowsCountInSection() -> Int
Надо передавать номер секции, или, если используется только одна секция, можно вместо 2 методом оставить только 
```Swift
var countOfRows: Int
```

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +        self.convertedData = [
Данные надо сразу закинуть в комплишен сервиса (пока эту функцию можно вызывать как хак в ините), потом будет проще и понятнее как интегрировать сеть

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        }
Давай не использовать внутри инициализации одного UI элементы другие элементы, надо вынести в какой-то setup метод

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        regionLabel.numberOfLines = 0
Тут точно 0? Может чем-то ограничим?

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        skillLabel.numberOfLines = 0
Аналогично

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        print("Button tapped")
Устарело?

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +            UIPasteboard.general.string = matchID
Лишняя табуляция?

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        skillStackView.bottomAnchor.constraint(lessThanOrEqualTo:contentView.bottomAnchor)
Тут не хватает табуляции еще одной

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        default : break
Можно тут вообще assert кидать, достаточно странно если сюда попадем

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/CopyIdButton.swift
> + class CopyIdButton: UIButton {
final

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +        winnersLabel.numberOfLines = 0
Надо явно ограничение задать

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +        self.selectionStyle = .none
self. можно опустить

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +        [winnersLabel,gameTimeLabel,matchEndTimeLabel,firstTeamScoreLabel,secondTeamScoreLabel].forEach{
Давай добавим переносы строк, массив плохо читается

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +        [winnersLabel,gameTimeLabel,matchEndTimeLabel,firstTeamScoreLabel,secondTeamScoreLabel].forEach{
И тут тоже

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +        winnersLabel.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 16),
Элементы массива должны быть с дополнительной табуляцией

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +            default : break //TO DO: заменить break
Тут тоже предлагаю сразу ассерт бросать

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +
Лишний перенос строки

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +        }
Элементы массива с дополнительной табуляцией, а у }  лишняя табуляция

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +
Лишний перенос строки (по крайней мере в коде выше был 1 перенос)

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +        cell.backgroundColor = ((indexPath.row % 2 == 0)&&(indexPath.row>3)) ? ColorPalette.alternativeBackground : ColorPalette.mainBackground
Сложно читать такое, хотябы так
```Swift
let isEven = indexPath.row % 2 == 0
let isMoreThanThree = indexPath.row > 3 // Тут я бы в названии отобразил зачем такое условие, не очевидно
(isEven && isMoreThanThree)
```

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +                print("error")
Надо убрать

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +    // TODO: update staqte обновляет у vc стейт (.loading/ .error)
Устарело?

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchPlayerCell.swift
> +        }
Надо вынести из инициализации UI элемента

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchPlayerCell.swift
> +        playerNameLabel.numberOfLines = 0
Надо наверное задать какое-то другое значение наверное? 2 или 3

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchPlayerCell.swift
> +           // playerImageView.image = data.playerImage
Надо убрать

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchPlayerCell.swift
> +        default : break
Тут можно ассерт кидать

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchPlayerCell.swift
> +}
Что-то не так с табуляцией

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/PlaeyrsTableHeaderCell.swift
> +        playerNameHeaderLabel.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 16),
Тут табуляция нужна для элементов массива

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/PlaeyrsTableHeaderCell.swift
> +        }
Лишняя табуляция

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/TeamMatchInfoTableViewCell.swift
> +        teamWinLabel.font = UIFont.systemFont(ofSize: 20) //изменить шрифт
Актуальный коммент?

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/TeamMatchInfoTableViewCell.swift
> +        teamNameLabel.numberOfLines = 0
Надо наверное задать что-то конкретное 2 или 3?

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/TeamMatchInfoTableViewCell.swift
> +        }
Надо убрать из инициализации UI элемента

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/TeamMatchInfoTableViewCell.swift
> +        [teamNameWinStack].forEach{contentView.addSubview($0)}
[teamNameWinStack].forEach{contentView.addSubview($0)}
```Swift
// 1 вариант
[
    teamNameWinStack
].forEach {
    contentView.addSubview($0)
}
// 2 вариант
contentView.addSubview(teamNameWinStack)
```

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/TeamMatchInfoTableViewCell.swift
> +        [teamNameWinStack].forEach{$0.translatesAutoresizingMaskIntoConstraints = false}
Аналогично тому что выше, но можно еще перенести в инициализацию UI элемента, как 3 вариант

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/TeamMatchInfoTableViewCell.swift
> +            default : break
Тут можно ассерт кидать

2021-12-15 07:04 UTC, just-evseev commented on DotaStats/Services/NetworkService.swift
> +
Лишние переносы строк

2021-12-15 16:45 UTC, aellita approved these changes

2021-12-15 16:45 UTC, aellita commented on DotaStats/Coordinator.swift
> +class Coordinator {
Кажется, этот файл лишний

2021-12-15 16:45 UTC, aellita commented on DotaStats/AppCoordinator.swift
>          tabBarController.setViewControllers(viewControllers, animated: false)
Здесь мы добавляем экран информации о матче, как еще одну вкладку в tab bar. Наверно, задумывалось попадать на него с экрана списка матчей.

2021-12-16 09:26 UTC, closed without merging