MatchInfoModule: Fixes and working version
DotaSirius/Dota2_Sirius pull request #116
Opened 2021-12-15 14:23 UTC by KamilKhairullin

2021-12-15 15:44 UTC, just-evseev approved these changes

2021-12-15 15:47 UTC, Antowkos requested changes

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/AppCoordinator.swift
> +    private func matchInfoModuleBuilder() -> MatchInfoModuleBuilder {
Фабричные методы лучше всего начинать со слова `make`
```suggestion
    private func makeMatchInfoModuleBuilder() -> MatchInfoModuleBuilder {
```

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/AppCoordinator.swift
>  final class StubImageNetworkService: ImageNetworkService {
А что здесь делает стабовый сервис? Он все еще нужен?

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/MatchInfoModuleBuilder.swift
> +        self.converter = converter
Зачем сохраняешь конвертер в билдере?

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +private extension MatchInfoConverterImp {
Вот лучше бы сделать наоборот. Сам конвертер умеет что-то конвертировать с помощью приватных функций и есть `extension`, в котором поддерживается протокол `MatchInfoConverter`

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    func mainMatchInfo(rawMatchInfo: MatchDetail) -> MainMatchInfo
С учетом того, что делает метод лучше бы его сигнатурку подправить до такой
```suggestion
    func mainMatchInfo(from rawMatchInfo: MatchDetail) -> MainMatchInfo
```
Для всех остальных подобных методов в протоколе можно сделать тоже самое

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +        _ = networkService.requestMatchDetail(id: matchId) { [weak self] result in
Тут либо надо сохранять токен запроса и отменять его при повторном вызове, либо убрать `_ = `

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +                print(error)
Принтить ошибки можно во время дебага, но пушить их в main без грамотной обработки в продакшене не стоит.

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +        updateView()
Кажется, что этот код вызывается до того, как `view` отображается на экране. Не будет ли здесь каких-нибудь проблем?

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        setUpConstraints()
Пжлст, давай `setup` писать однообразно. Посмотри по всему коду
```suggestion
        setupConstraints()
```

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        }
Перенеси в настройки самих вьюх, пж

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +            matchIdCopyButton.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 16),
лучше циферку 16 вынести в отдельную переменную, обозвать как-то получше, например `inset` и везде юзать. Посмотри везде, пж

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +        // TO DO: Errors
```suggestion
        // TODO: Errors
```

2021-12-15 15:47 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +            setUpConstraints()
На каждый `.success` будет добавляться таблица

2021-12-15 18:55 UTC, KamilKhairullin commented on DotaStats/AppCoordinator.swift
>  final class StubImageNetworkService: ImageNetworkService {
Используется в другом модуле. Для нашего не нужен, но без него не запускается. Так что вопрос, скорее всего, к тем, кто писал модуль SearchPlayerModule

2021-12-15 19:05 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +        _ = networkService.requestMatchDetail(id: matchId) { [weak self] result in
> Тут либо надо сохранять токен запроса и отменять его при повторном вызове, либо убрать `_ =`

Без `_ =` всплывает warning 
Result of call to 'requestMatchDetail(id:completion:)' is unused

2021-12-15 19:10 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +        updateView()
> Кажется, что этот код вызывается до того, как `view` отображается на экране. Не будет ли здесь каких-нибудь проблем?

Проблем возникнуть не должно. Тут скорее неправильное название метода. Метод делает запрос данных из сети и после этого обновляет переменную state. А во view данные уходят в didSet переменной state, предварительно законверченные. Я думаю, стоит переименовать метод.

2021-12-16 07:13 UTC, aellita approved these changes

2021-12-16 08:00 UTC, NickaKos11 commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        setUpConstraints()
сделала

2021-12-16 08:01 UTC, NickaKos11 commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        }
сделала

2021-12-16 08:01 UTC, NickaKos11 commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +            matchIdCopyButton.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 16),
сделала

2021-12-16 09:27 UTC, Antowkos requested changes

2021-12-16 09:27 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Model/MatchesInfoModuleState.swift
> +    case error(HTTPError)
Лучше бы эту штуку конвертировать в удобоваримую ошибку для вьюхи

2021-12-16 09:27 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +        _ = networkService.requestMatchDetail(id: matchId) { [weak self] result in
Почитай про `@discardableResult`

2021-12-16 09:27 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        matchIdCopyButton.setTitle("Copied!", for: .normal)
Будет здорово, если спустя какое-то время (например, 5 секунд) заголовок кнопки вернется в свое первоначальное состояние

2021-12-16 09:27 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +        let tapActionHideError = UITapGestureRecognizer(target: self, action: #selector(handleTap(_:)))
Сейчас название этой переменной говорит о том, что в ней хранится ошибка. Лучше назвать ее примерно так
```suggestion
        let tapActionGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTap(_:)))
```

2021-12-16 09:27 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +    @objc func handleTap(_: UITapGestureRecognizer) {
Не самое лучшее название для функции. По имени этой функции кажется, что внутри нее обрабатываются любые касания, а это не так. Надо в названии отразить что конкретно она делает

2021-12-16 12:01 UTC, Antowkos reviewed
Про возврат надписи при копировании не забудьте, пжлст

2021-12-16 15:00 UTC, Antowkos approved these changes

2021-12-16 15:02 UTC, merged