Creating models
DotaSirius/Dota2_Sirius pull request #39
Opened 2021-12-10 10:00 UTC by aellita

2021-12-10 12:36 UTC, vrmaks requested changes

2021-12-10 12:36 UTC, vrmaks commented on DotaStats/Data/Networking/NetworkingModels/Matches.swift
> +struct Matches : Codable {
import Foundation
Codable -> Decodable везде

2021-12-10 12:36 UTC, vrmaks commented on DotaStats/Data/Networking/NetworkingModels/Players.swift
> +struct Estimate {
Занести внутрь корневого ответа.
Либо просто выше, либо через extension PlayersResult

2021-12-10 12:36 UTC, vrmaks commented on DotaStats/Data/Networking/NetworkingModels/ProMatches.swift
> +//let jsonDecoder = JSONDecoder()
Тесты отдельно.

2021-12-11 11:20 UTC, aellita commented on DotaStats/Data/Networking/NetworkingModels/Matches.swift
> +struct Matches : Codable {
Поправлены замечания, теперь все в  ветке `mergingModelsAndNetworkingService`.

2021-12-11 11:25 UTC, vrmaks commented
Сделано в другом пуле #41

2021-12-11 11:25 UTC, closed without merging