Добавление Networking моделей и тестов к ним + смена структуры схем
DotaSirius/Dota2_Sirius pull request #41
Opened 2021-12-10 12:44 UTC by delet-dis

2021-12-10 13:32 UTC, straivi commented on DotaStats/Data/Networking/NetworkingModels/ProMatches.swift
> +    let leagueid : Int
`leagueId`

2021-12-10 13:33 UTC, straivi commented on DotaStats/Data/Networking/NetworkingModels/ProMatches.swift
> +//let jsonData: Data
думаю стоит почистит коменты из кода

2021-12-10 13:44 UTC, straivi commented on DotaStatsTests/Networking/Models/MatchesDecodingTest.swift
> +        XCTAssertEqual(decodedData.matches[0].matchId, 6312319970)
nit: может инитить структуру и сравнивать две структуры, на случай если изменим набор полей в структуре, а то так мы только определенные поля проверяем

2021-12-10 14:08 UTC, vrmaks commented on DotaStats/Data/Networking/NetworkingModels/ProMatches.swift
> +    let leagueid : Int
Так и называется в документации.

2021-12-10 14:10 UTC, vrmaks commented
git merge --no-ff origin/main

2021-12-10 14:27 UTC, aellita commented on DotaStats/Data/Networking/NetworkingModels/ProMatches.swift
> +//let jsonData: Data
Убрала

2021-12-10 16:31 UTC, vrmaks requested changes

2021-12-10 16:31 UTC, vrmaks commented on DotaStats/AppDelegate.swift
> +
nit: ждем форматтер

2021-12-10 16:31 UTC, vrmaks commented on DotaStats/Data/Networking/Interfaces/NetworkService.swift
> +struct NetworkService {
Ждем протокол для того чтобы закрыть нашу реализацию.

2021-12-10 16:31 UTC, vrmaks commented on DotaStats/Data/Networking/NetworkingModels/Matches.swift
> +        let time : Int
Во вложенных структурах тоже стоит пересмотреть опциональность полей.

2021-12-10 16:31 UTC, vrmaks commented on DotaStats/Data/Networking/Service/HTTPError.swift
> +    case success = "Successful Network Request"
Странно видеть success в enum ошибок, подскажи какая была идея?

2021-12-10 16:31 UTC, vrmaks commented on DotaStats/Data/Networking/Service/NetworkCommunicationResult.swift
> +enum NetworkCommunicationResult<T> {
Достаточно просто NetworkResult, не нужен communication, и в целом он вообще заменяется на:
Swift Result<T, Error> подскажи в чем тут была идея новой сущности?

2021-12-10 16:31 UTC, vrmaks commented on DotaStats/Data/Networking/Service/HTTPNetworkResponse.swift
> +    static func handleNetworkResponse(for response: HTTPURLResponse?) -> NetworkCommunicationResult<String> {
Тут сразу возвращается String - выглядит довольно странно, подскажи какой тут ожидается флоу?

2021-12-10 16:31 UTC, vrmaks commented on DotaStats/Data/Networking/Interfaces/NetworkService.swift
> +        if case request.headers = request.headers {
nit: можно заменить
```
request.headers.forEach {
    print($0.key)
    print($0.value)
}

```

2021-12-11 10:57 UTC, vrmaks commented on DotaStats/Data/Networking/Service/HTTPMethod.swift
> +enum HTTPMethod: String {
Можно перенести внутрь HTTPRequest

2021-12-11 10:57 UTC, vrmaks commented on DotaStats/Data/Networking/Service/HTTPRequest.swift
> +
Сюда JSONDecoder.keyEncodingStrategy + dateDecodingStrategy

2021-12-11 10:57 UTC, vrmaks commented on DotaStats/Data/Networking/Service/HTTPRequest.swift
> +
nit: +queryItems: [URLQueryItem] все это в качестве развития на будущее.

2021-12-11 11:27 UTC, merged