Matches module, presenter implementation
DotaSirius/Dota2_Sirius pull request #64
Opened 2021-12-13 11:34 UTC by NastyRu

2021-12-13 12:03 UTC, Solnyshkoo approved these changes

2021-12-13 14:18 UTC, Antowkos requested changes

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Model/MatchCellType.swift
> +    case matchViewState (TournamentViewState.MatchViewState)
Возможно, вкусовщина, но чаще всего сам кейс и скобочки не отделяются

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Model/MatchCollectionPresenterData.swift
> +    }
Может лучше заюзать `IndexPath`?

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Model/TournamentViewState.swift
> +        var score: String // "radiantScore:direScore"
Этот коммент похож на описание того, что хранится в этом поле. Поэтому, надо либо переделать его в квик-док, либо удалить

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +            oldValue.token?.cancel()
А разве надо после обновления стейта отменять запрос?

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Model/MatchesModulePresenterState.swift
> +    var token: Cancellable? {
Непонятно что это за токен такой. Может его обозвать как-нибудь поконкретнее?

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                    matches.sort { $0.startTime < $1.startTime }
Может лучше сделать так, чтобы `Match` поддерживал протокол `Comparable`?

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                    convertMatches(matches: matches)
Если чуть изменить сигнатуру функции, то может получиться так
```suggestion
                    convert(matches)
```
Ну и по имени кажется, что функция должна что-то вернуть. Если в функции как-то хендлятся матчи, то лучше ее переименовать во что-то типа `handle(matches)`

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                    view?.updateState(matchesModuleState: MatchesModuleViewState.success)
Тут тоже можно улучшить сигнатуру, например так.
```suggestion
                    view?.update(state: .success)
```

Даже если не улучшать сигнатуру, вот так полностью `MatchesModuleViewState.success` писать енамы не стоит, лучше опускать первую часть по возможности до `.success`

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                    view?.updateState(matchesModuleState: MatchesModuleViewState.error(error.rawValue))
А почему передаем `rawValue`?

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +            case .none, .loading:
А что за case `.none`? Кажется, что на него должен быть другой обработчик

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +    }
Можно тело этой функции упаковать в `didSet` свойства `view`

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +        let token = matchesService.requestProMatches() { [weak self] result in
Если не ошибаюсь, то `()` можно опустить 🤔
```suggestion
        let token = matchesService.requestProMatches { [weak self] result in
```

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +            self.state = .result(result)
Не обязательно анрапить стейт, можно написать так
```suggestion
            self?.state = .result(result)
```

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +        state = .loading(token)
Я бы эту строчку написал самой первой в методе

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                    radiantTeam: match.radiantName ?? "Radiant team",
Строки желательно упаковывать в `LocalizedString`. Вообще для ресурсов можно использовать `swiftgen`, он прекрасно справляется с генерацией ресурсов (строки/картинки/цвета)

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                    score: "\(match.radiantScore):\(match.direScore)",
Можно сделать вычисляемую переменную `score` в `Match`

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                let newMatch = MatchCollectionPresenterData(
Это же не `match`, а `tournament` 🤔

2021-12-13 14:18 UTC, Antowkos commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +    private func convertMatches(matches: [Match]) {
Кажется, что этот метод в целом работает как-то запутанно, подойди ко мне, надо будет обсудить что здесь происходит )

2021-12-14 09:10 UTC, NastyRu commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +        state = .loading(token)
она использует token, который нужно сначала объявить

2021-12-14 09:55 UTC, just-evseev requested changes

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/Model/MatchesModulePresenterState.swift
> +    case result(Result<[Match], HTTPError>)
Давай разделим на 2 статуса тут
```Swift
case .success([Match])
case .error(HTTPError)
```

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/Model/MatchesModulePresenterState.swift
> +    case result(Result<[Match], HTTPError>)
Давай разделим на 2 статуса тут
```Swift
case .success([Match])
case .error(HTTPError)
```

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/Model/TournamentViewState.swift
>          var radiantTeam: String
А у тебя используется мутабельность параметров или может лучше let?

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +        secondTeam.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -15)
Тут отступ надо проставить, SwiftFormat не помогает?

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +
? SwiftFormat полечит наверное

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +        addView()
Это надо делать не в layoutSubviews, а в ините

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +        let cell = gesterRecognizer.view as! ListTournamentsCell
as! -> as?

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +
?

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +//        tableView.reloadSections(NSIndexSet(index: section) as IndexSet, with: .automatic)
?

2021-12-14 09:55 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +        print("eeeeeeeeeeeeeeeeeeeeeeeee")
?

2021-12-14 10:03 UTC, vrmaks requested changes

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +    func matchesModule(_ module: MatchesModuleInput, didSelectPlayer matchId: Int)
Тут что-то неочевидное - выбрали игрока, но параметр - matchId - подскажи по итогу выбираем ведь матч?

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                    matches.sort { $0 < $1 }
nit: Вот тут можно было по месту указать какая именно нужна сортировка: $0.startTime < $1.startTime

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +        for match in matches {
Это выглядит как классический reduce:
```
let leaguesDictionary = matches.reduce(into: [String: [Match]]()) { result, match in
    let leagueName = match.leagueName
    var leagueMatches = result[leagueName] ?? []

// вот тут можно конвертнуть если нужно
//   let matchViewState = self.convert(match)

   leagueMatches.append(match)
   result[leagueName] = leagueMatches
}
```

А после конвертнуть её в уже в [TournamentViewState]

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +class ListMatchesCell: UITableViewCell {
final

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +    func addView() {
private и стоит переименовать либо в addViews, либо просто в setup.

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +        firstTeam.centerYAnchor.constraint(equalTo: centerYAnchor),
Прогнать форматтер - не хватает инсетов - нужно еще +4 пробела

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +class ListTournamentsCell: UITableViewHeaderFooterView {
final

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +    func addView() {
private

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +        let cell = gesterRecognizer.view as! ListTournamentsCell
Подскажи, а зачем эта сложная история с кастами, это ведь self?

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +            title.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 20),
trailing тоже стоит добавить

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +        super.viewDidLoad()
Пустые имплементации стоит удалять

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +    func setUpLabel() {
private здесь и ниже

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +        print("eeeeeeeeeeeeeeeeeeeeeeeee")
debug code?)

2021-12-14 10:03 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +//        output?.cellTapped(indexPath: section)
Подскажи, тут что-то должно быть?

2021-12-14 12:34 UTC, vrmaks commented on DotaStats/AppCoordinator.swift
> +            matchesService: MatchesServiceImp(
Парой строчек выше тоже стоит заменить создание NetworkServiceImp

2021-12-14 12:34 UTC, vrmaks commented on DotaStats/AppDelegate.swift
> +         window!.rootViewController = root
1. MainTabBarController тут уже не нужно создавать и сетать.
2. Для улучшение читабельности кода можно разделить абзацами логические куски
```
window = UIWindow(frame: UIScreen.main.bounds)

let appCoordinator = ...
```

2021-12-14 12:34 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                matches.sort()
Вот этот sort занести в convert т.к. код внутри сильно рассчитывает на это
**Upd**: увидел что внутри уже есть сортировка, тогда эту строчку можно просто удалить

2021-12-14 13:31 UTC, Solnyshkoo commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +    func addView() {
переименовала, но не могу сделать private так как на данный момент функция вызывается из MatchesModuleViewController

2021-12-14 13:49 UTC, NastyRu commented on DotaStats/AppCoordinator.swift
> +            matchesService: MatchesServiceImp(
так еще PlayersNetwork не реализован

2021-12-14 14:25 UTC, europeec approved these changes

2021-12-14 14:25 UTC, europeec commented on DotaStats/AppCoordinator.swift
> +        tabBarController.setViewControllerImages([NSLocalizedString("players", comment: ""),
для чего тут использовать `NSLocalizedString`? Мы же это используем как название картиночки

2021-12-14 14:25 UTC, europeec commented on DotaStats/Modules/MatchesModule/Model/MatchesModulePresenterState.swift
> +    case loading(Cancellable?)
не нашел отмены запросов, для чего тогда хранить токен? `case loading`

2021-12-14 14:25 UTC, europeec commented on DotaStats/Modules/MatchesModule/Model/MatchesModulePresenterState.swift
> +extension MatchesModulePresenterState {
если запросы не отменяются - то бесполезно

2021-12-14 14:25 UTC, europeec commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +        label.font = UIFont.systemFont(ofSize: 17, weight: .bold)
nit: может вынести размер шрифта в константы какие-нибудь?

2021-12-14 14:35 UTC, NastyRu commented on DotaStats/AppCoordinator.swift
> +        tabBarController.setViewControllerImages([NSLocalizedString("players", comment: ""),
Чтобы строка просто так не висела, упаковала в LocalizedString

2021-12-14 14:49 UTC, just-evseev requested changes

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/AppCoordinator.swift
> +        tabBarController.setViewControllerImages([NSLocalizedString("players", comment: ""),
Это какой-то временный хак? Если нет, то опять несоответствие метода и того что отправляем. Метод хочет картинки, а отправляем ему строки

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Data/Networking/NetworkingModels/Match.swift
> +	let radiant : Bool?
Лишняя табуляция кажется

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/MainTabBarController.swift
>          }
Давай отдельно сделаем просто параметр 
```Swift
var tabImageNames: [String]
```
Отдельно метод 
```Swift
func configurateTabs() { /*...*/ }
```
И не будем вызывать извне, а будем применять при сете вью контроллеров

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/Model/MatchCollectionPresenterData.swift
> +    var matches: [TournamentViewState.MatchViewState]
Тут точно все свойства var или только isOpen?

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +        for match in sortedMathes {
```Swift
for match in matches.sort() { /*...*/ }
```

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                tournaments[index].matches.append(newMatch)
Тут логичнее в if let взять не firstIndex, а first, чтобы потом его использовать

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/Presenter/MatchesModulePresenter.swift
> +                )
Как будто что-то не так с форматированием

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +    lazy var firstTeam: UILabel = {
private

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListMatchesCell.swift
> +        label.numberOfLines = 5
Почему тут 5, а во втором 3?

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/ListTournamentsCell.swift
> +    lazy var title: UILabel = {
private

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +    private func setUpLabel() {
В целом можно было бы и в 1 метод сделать setup, но не критично

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +            print("error")
?

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +        tableView.reloadData()
А не получается через reloadSection у tableView?

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +        cell.secondTeam.text = data?.direTeam.trimmingCharacters(in: .whitespaces)
Так не пойдет, обсуждали что надо делать через протокол

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +        }
Конфигурация формируется в презенторе и применяется в вьюшке, а не в ViewControllerе

Надо вынести в презентор определение параметров и убрать в вью применение их

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(withIdentifier: ListMatchesCell.reuseIdentifier, for: indexPath) as? ListMatchesCell else { return UITableViewCell() }
Должно быть data.reuseIdentifier и это свойство реализовано должно быть у enum с типом данных

2021-12-14 14:49 UTC, just-evseev commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +            label.topAnchor.constraint(equalTo: view.topAnchor, constant: 80),
Далековато, вроде обсуждали? Надо поправить мб? Если не хочешь исправлять, приведи референсы других приложений или ссылку на дизайн гайдлайны

2021-12-14 14:55 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/MatchesModuleBuilder.swift
> +    let viewControler: MatchesModuleViewController
**typo**: viewControler -> viewControl**l**er

2021-12-14 14:55 UTC, vrmaks commented on DotaStats/Modules/MatchesModule/View/MatchesModuleViewController.swift
> +            spiner.color = ColorPalette.accent
nit: стоит вынести в инициализацию спиннера

2021-12-14 17:14 UTC, vrmaks approved these changes
Чиним все завтра в отдельном пуле.

2021-12-14 17:14 UTC, merged