Добавил сервис для поиска игроков
DotaSirius/Dota2_Sirius pull request #72
Opened 2021-12-13 14:01 UTC by delet-dis

2021-12-13 14:05 UTC, just-evseev requested changes
Пингани когда все пулы вольешь, которые предшествуют этому)

2021-12-13 14:42 UTC, vrmaks requested changes

2021-12-13 14:42 UTC, vrmaks commented on DotaStats/Services/PlayerSearchService.swift
> +        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX"
Откомментил 2 пула назад, что стоит экстракт сделать =)

2021-12-13 14:42 UTC, vrmaks commented on DotaStats/Services/PlayerSearchService.swift
> +        }
```
networkClient.processRequest(
    request: createRequest(name)),
    completion: closure
)
```

2021-12-13 14:42 UTC, vrmaks commented on DotaStats/Services/PlayerSearchService.swift
> +            queryItems: [HTTPRequestQueryItem("q", name)],
Вероятно вот тут нужно делать escaping.

2021-12-13 15:34 UTC, just-evseev commented on DotaStats/Services/PlayerSearchService.swift
> +
Давай удалим коменты

2021-12-14 11:36 UTC, vrmaks approved these changes

2021-12-14 11:37 UTC, merged