Сделал загрузку картинок в presenter для игроков в поиске
DotaSirius/Dota2_Sirius pull request #77
Opened 2021-12-13 15:05 UTC by europeec

2021-12-13 18:12 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/Model/PlayerSearch.swift
> +    init(from search: Search) {
nit: для структур автоматически генерируется init - моно удалить

2021-12-13 18:12 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +                players = result
На didSet players нужно отменять все загрузки картинок и резетить токены загрузки.

2021-12-13 18:12 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +                switch result {
nit: стоит добавить guard let set = self, чтобы не проверять все что происходит ниже.

2021-12-13 18:12 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +                    self?.imageRequestTokens[indexPath] = nil
self?.imageRequestTokens[indexPath] = nil стоит делать в любом из кейсов (успех, неуспех)

2021-12-14 07:45 UTC, just-evseev commented on DotaStats/Modules/SearchPlayerModule/View/SearchPlayerModuleViewController.swift
>      var count: Int { get }
Я бы уточнил count чего (countOfRows или countOfSection)

2021-12-14 07:45 UTC, just-evseev commented on DotaStats/Services/NetworkService.swift
> +    func playersByName(_ name: String, completion: @escaping (Result<[Search], HTTPError>) -> Void) -> Cancellable?
А почему поменяли название структуры? Раньше искали массив игроков (что тоже не правильно), а теперь грузим массив поисков?

Можно сделать что-то типо:
PlayerProfile/
PlayerProfileFromSearch/
ShortPlayerInfo/
PlayerInfo/
SearchPlayerResult/
PlayerSearchResult

2021-12-14 07:45 UTC, just-evseev commented on DotaStats/Modules/SearchPlayerModule/Model/PlayerSearch.swift
> +struct PlayerSearch {
Не очень очевидно из названия что это такое
Лучше как-то уточнить
Player/PlayerInfoFromSearch/PlayerInfo

В конце для профиля можно даже наследоваться от профиля в поиске, потому что кажется информация может переиспользоваться на экранах

2021-12-14 09:28 UTC, just-evseev approved these changes

2021-12-14 10:38 UTC, europeec commented on DotaStats/Modules/SearchPlayerModule/View/SearchPlayerModuleViewController.swift
>      var count: Int { get }
поменял на `countOfRows: Int`

2021-12-14 10:39 UTC, europeec commented on DotaStats/Services/NetworkService.swift
> +    func playersByName(_ name: String, completion: @escaping (Result<[Search], HTTPError>) -> Void) -> Cancellable?
поменял на  `SearchPlayerResult`

2021-12-14 10:40 UTC, europeec commented on DotaStats/Modules/SearchPlayerModule/Model/PlayerSearch.swift
> +struct PlayerSearch {
информация немного разная, поэтому наследоваться не может, поменял на:  `PlayerInfoFromSearch`

2021-12-14 10:42 UTC, europeec commented on DotaStats/Modules/SearchPlayerModule/Model/PlayerSearch.swift
> +    init(from search: Search) {
`init(from search: Search)` использовал для инициализации от другой структуры

2021-12-14 10:42 UTC, europeec commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +                players = result
исправил

2021-12-14 10:42 UTC, europeec commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +                switch result {
добавил

2021-12-14 10:43 UTC, europeec commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +                    self?.imageRequestTokens[indexPath] = nil
исправил

2021-12-14 11:11 UTC, vrmaks requested changes

2021-12-14 11:11 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +            cancelAllLoading()
Лучше добавить более специфичный нейминг - cancellAllImagesTokens.

2021-12-14 11:11 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +    init(output: SearchPlayerModuleOutput, playerSearchService: PlayerSearchService, imageNetworkService: ImageNetworkService) {
```suggestion
    init(
        output: SearchPlayerModuleOutput,
        playerSearchService: PlayerSearchService,
        imageNetworkService: ImageNetworkService
    ) {
```

2021-12-14 11:11 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +    }
+ imageRequestTokens remove all

2021-12-14 11:11 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +        if let urlString = players[indexPath.row].avatarFull,
let player = players[indexPath.row]

loadPlayerAvatar(player: ***)  { [weak self] in
 self?.view.reload(at: indexPath)
}

return player


func loadPlayerAvatar(player: Player., completion: @escaping () -> Void) {
    guard player.avatar == nil,
             let urlString = player.avatarFull,
             let url = URL(string: urlString) else {
                return 
     }

    let imageRequestToken = imageNetworkService.load ...
      player.avatar = image
   }

}

2021-12-14 12:02 UTC, vrmaks requested changes

2021-12-14 12:02 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +            }
Удалить токен по urlString + completion()

2021-12-14 12:37 UTC, vrmaks commented on DotaStats/Modules/SearchPlayerModule/SearchPlayerModulePresenter.swift
> +                completion()
nit: Можно просто completion?()
+токен решил не чистить?

2021-12-14 12:56 UTC, vrmaks approved these changes

2021-12-14 13:07 UTC, vrmaks approved these changes

2021-12-14 14:36 UTC, straivi approved these changes

2021-12-14 14:53 UTC, just-evseev approved these changes

2021-12-14 16:21 UTC, merged