MatchInfoModule: View and Presenter+Converter for review
DotaSirius/Dota2_Sirius pull request #80
Opened 2021-12-13 17:12 UTC by KamilKhairullin

2021-12-13 17:27 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/View/PlayerListTableViewCell.swift
> +////
Файл должен быть удален, но почему-то остался..

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Model/MatchTableViewData.swift
> +    let TableContent: [MatchTableViewCellData]
Параметры с маленькой буквы

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Model/PlayerList.swift
> +    //let playerImage: UIImage
?

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +        return MainMatchInfo(winnersLabelText: winnersLabelText, gameTimeLabelText: gameTimeLabelText, firstTeamScoreLabelText: firstTeamScoreLabelText, secondTeamScoreLabelText: secondTeamScoreLabel
Аналогично везде
```Swift
return MainMatchInfo(
    winnersLabelText: winnersLabelText, 
    gameTimeLabelText: gameTimeLabelText, 
    firstTeamScoreLabelText: firstTeamScoreLabelText, 
    secondTeamScoreLabelText: secondTeamScoreLabelText, 
    matchEndTimeLabelText: matchEndTimeLabelText
)
```

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +class MatchInfoConverterImp: MatchInfoConverter {
Задача конвертера принять в себя ответ запроса и обработать его
Тут я вижу что он еще держит ссылку на сервис, это не верно. Сервис должен держать ссылку на конвертер и после удачного завершения запроса инициализироваться и выполнять конвертацию

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    private var matchInfoRaw: MatchDetail
Мне кажется сырые данные должны лежать в презенторе, а конвертер содержит static методы которые преобразуют сырые данные в необходимые viewData

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    }
Пример того как мне кажется должны выглядить методы конвертера:
```Swift
static func getAdditionalMatchInfo(matchInfoRaw: MatchDetail) -> AdditionalMatchInfo {
    let matchIdLabelText = "\(matchInfoRaw.matchId)"
    let regionLabelText = convert(region: matchInfoRaw.region)
    let skillLabelText = convert(skillBracket: matchInfoRaw.skill)
    return AdditionalMatchInfo(
        matchIdLabelText: matchIdLabelText, 
        regionLabelText: regionLabelText, 
        skillLabelText: skillLabelText
    )
}
```

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    func convert(playerName: String?) -> String {
Вроде все эти методы convert... должны быть private

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +            return "-"
Не хотим заменять на что-то более осмысленное (например Anonymous)
Аналогично дальше

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    // MARK: - MainMatchInfo converters
Можно вынести отдельные виды конверторов в private extension

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +    func getRowsCountInSection() -> Int
А тут номер секции не нужно передавать?

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +        ]
Эта штука должна быть при смене статуса презентора на success
А я сейчас вообще не вижу где у нас код работы со статусами

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        matchIdCopyButton.addTarget(self, action: #selector(copyMatchIdButtonPressed), for: .touchUpInside)
Давай это вынесем в инициализацию Button и дальше все также

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        [matchIdCopyButton, regionStackView, skillStackView].forEach { $0.translatesAutoresizingMaskIntoConstraints = false }
Можно вынести в инициализацию элементов

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        matchIdCopyButton.titleLabel?.font = UIFont.systemFont(ofSize: 20)
Тут кстати можно опускать UIFont, останется:
```Swift
matchIdCopyButton.titleLabel?.font = .systemFont(ofSize: 20)
```

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/DetailedMatchInfoCellConfigurable.swift
> +    // func configure(with data: String)
?

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/CopyIdButton.swift
> +class CopyButton: UIButton {
Может сделать HighlightedButton и в синит ему прикидывать цвета? Тогда будет удобно переиспользовать в других местах при необходимости

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +        cell.configure(with: data)
А почему в итоге используется структура? На enum не собирается?

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/MatchPlayerCell.swift
> +        // playerImageView.image = data.playerImage
?

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/PlayerListTableViewCell.swift
> +////
Надо удалить получается?

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/TeamMatchInfoTableViewCell .swift
> +//
Комментарии удаляем

2021-12-14 08:25 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/View/PlayersTableHeaderCell.swift
> +        [playerInfoHeaderStack].forEach { contentView.addSubview($0) }
```Swift
contentView.addSubview(playerInfoHeaderStack)
```

2021-12-14 16:15 UTC, Antowkos requested changes

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/MainTabBarController.swift
> +        let network = NetworkServiceImp()
Лучше писать названия переменных полностью. Тем более, это надо сделать всего 1 раз, автокомплит потом будет тебе помогать
```suggestion
        let networkService = NetworkServiceImp()
```

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Model/PlayerList.swift
> +    //let playerImage: UIImage
Немного дополню вопрос Ильи. Зачем здесь закомментированное свойство?

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    func getRadiantMatchInfo() -> TeamMatchInfo
я бы опустил слово `get`. В iOS программинге оно не особо используется

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +class MatchInfoConverterImp: MatchInfoConverter {
Поддерживаю предыдущего оратора почти во всем. Спорным для меня только остается вопрос того, что в сервисе нужна ссылка на конвертер. Я бы все-таки их разделил и просто заинжектил конвертер в модуль и конвертировал матчи непосредственно в модуле

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    func getRadiantMatchInfo() -> TeamMatchInfo
А еще конвертер исходя из названия должен конвертировать. Для конвертации нужно получать данные на вход и отдавать конвертированные на выход. В общем, методы должны поменяться

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +        matchInfoRaw = MatchDetail(matchId: 12345678, barracksStatusDire: nil, barracksStatusRadiant: nil, chat: nil, cluster: nil, direScore: 44, draftTimings: nil, duration: 1371, engine: nil, firs
А эта строка временная?

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    // MARK: - PlayerList converters
Нужна пустая строка между концом функции и марком

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    func convert(playerName: String?) -> String {
Поддерживаю

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +            return "-"
Поддерживаю

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +    // TODO: - Integration with Coordinator
Эта тудушка совсем необязательна

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +            MatchTableViewCellType.matchPlayerInfo(converter.getPlayerInfo(number: 9)),
Лучше подобное вынести в отдельный массив и добавить сюда после формирования `convertedData`
```suggestion
            for index in 0..<10 {
                MatchTableViewCellType.matchPlayerInfo(converter.getPlayerInfo(number: index))
            }
```

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        setUpConstraints()
Давай в едином стиле напишем?
```suggestion
        setupConstraints()
```

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        matchIdCopyButton.addTarget(self, action: #selector(copyMatchIdButtonPressed), for: .touchUpInside)
Вери жирный плюс 👍 Все, кроме лэйаута лучше убирать в инит самой переменной.

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/AdditionalMatchInfoTableViewCell.swift
> +        default: break
Лучше не использовать `default`, чтобы при расширении енама здесь случилась ошибка и не дала бы не обработать какой-нибудь кейс случайно

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/MatchInfoModuleBuilder.swift
> +        converter = MatchInfoConverterImp(networkService: networkService)
Все зависимости должны прокидываться извне. Никаких скрытых зависимостей для внешних сервисов!

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +        setUpConstraints()
Посмотри, пжлст, в этой ячейке те же замечания, что и в `AdditionalMatchInfoTableViewCell`

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MainMatchInfoTableViewCell.swift
> +        firstTeamScoreLabel.topAnchor.constraint(equalTo: winnersLabel.bottomAnchor, constant: 8).isActive = true
Пожалуйста, вынеси все волшебные цифры в осознанные константы

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +    // TODO: update staqte обновляет у vc стейт (.loading/ .error)
Не надо оставлять подобные комментарии

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MatchInfoViewController.swift
> +        setUpConstraints()
Проверь все вызовы `setup`, пжлст

2021-12-14 16:15 UTC, Antowkos commented on DotaStats/Modules/MatchInfoModule/View/MatchPlayerCell.swift
> +        setUpConstraints()
И эту ячейку глянь, пж

2021-12-14 18:25 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Model/PlayerList.swift
> +    //let playerImage: UIImage
Осталось с времен, когда не знали, как передавать картинку. Потому, что для того, чтобы передать ее, нужно было импортить UIKit в Presenter.

2021-12-14 18:25 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Model/PlayerList.swift
> +    //let playerImage: UIImage
Осталось с времен, когда не знали, как передавать картинку. Потому, что для того, чтобы передать ее, нужно было импортить UIKit в Presenter.

2021-12-14 19:07 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    private var matchInfoRaw: MatchDetail
Вопрос, как делать DI, если все методы будут static?

2021-12-14 19:14 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +        matchInfoRaw = MatchDetail(matchId: 12345678, barracksStatusDire: nil, barracksStatusRadiant: nil, chat: nil, cluster: nil, direScore: 44, draftTimings: nil, duration: 1371, engine: nil, firs
> А эта строка временная?

Да!

2021-12-14 19:19 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    }
> Пример того как мне кажется должны выглядить методы конвертера:
> 
> ```swift
> static func getAdditionalMatchInfo(matchInfoRaw: MatchDetail) -> AdditionalMatchInfo {
>     let matchIdLabelText = "\(matchInfoRaw.matchId)"
>     let regionLabelText = convert(region: matchInfoRaw.region)
>     let skillLabelText = convert(skillBracket: matchInfoRaw.skill)
>     return AdditionalMatchInfo(
>         matchIdLabelText: matchIdLabelText, 
>         regionLabelText: regionLabelText, 
>         skillLabelText: skillLabelText
>     )
> }
> ```

Вопрос об этом выше. 
Дублирую:
(Вопрос, как делать DI, если все методы будут static? Если я хочу добавить возможность использовать кастомные конверторы, conforming to MatchInfoConverter protocol?)

2021-12-14 19:21 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    func convert(playerName: String?) -> String {
Будет сделано!

2021-12-14 19:38 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoConverter.swift
> +    // MARK: - MainMatchInfo converters
> Можно вынести отдельные виды конверторов в private extension

В некоторых из методов может быть добавлена логика. Например, в playerRankTier данные приходят в виде Int. Ранги в доте называются "Legend", "Immortal" и тд. И когда я найду правильную конвертацию, я это добавлю. (В апи расшифровки я не нашел). 

Я не понял, что ты имеешь ввиду:
- То, что convert(stat...) используется для Kill, Death, Assist, Gold и тд и из-за этого его нужно вынести в private extension

ИЛИ

- То, что некоторые convert(...) имеют одинаковую структуру и из-за этого их нужно объединить в что-то вроде convert(number: Int?) -> String и вынести в private extension

ИЛИ

что-то другое?

2021-12-14 19:43 UTC, KamilKhairullin commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +    func getRowsCountInSection() -> Int
добавил

2021-12-15 08:03 UTC, just-evseev commented on DotaStats/Modules/MatchInfoModule/Presenter/MatchInfoModulePresenter.swift
> +    func getRowsCountInSection() -> Int
Кажется у вас вообще только 1 секция, наверное стоит вместо 2 методов сделать 1 - 
```Swift
var numberOfRows: Int { get }
```

2021-12-16 09:27 UTC, closed without merging