#68 create universal image load component
DotaSirius/Dota2_Sirius pull request #97
Opened 2021-12-14 14:28 UTC by straivi

2021-12-14 14:48 UTC, europeec approved these changes

2021-12-14 14:48 UTC, europeec commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +                break
может показывать какую-то картинку, если ничего не скачалось?

2021-12-14 14:48 UTC, europeec commented on DotaStats/Services/ImageService.swift
> +import UIKit
`import UIKit`

2021-12-14 15:02 UTC, vrmaks requested changes

2021-12-14 15:02 UTC, vrmaks commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +class CachedImageView: UIImageView {
final

2021-12-14 15:02 UTC, vrmaks commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +        imageLoader.loadWithUrl(url) { result in
1. [weak self]
2. Нужно делать cancel предыдущего запроса иначе будет гонка

2021-12-14 15:02 UTC, vrmaks commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +        gradientLayer.frame = bounds
Нужен флаг isAnimating и guard на него.
Иначе вызвав 2 раза loadWithURL получим несколько анимаций.

2021-12-14 15:02 UTC, vrmaks commented on DotaStats/Services/ImageService.swift
> +class ImageServiceImp: ImageService {
final

2021-12-15 08:17 UTC, Antowkos requested changes

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +    }
Кажется, что этот инит можно выкинуть, а извне вызывать `init(frame: .zero)`

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +    func loadWithUrl(_ url: String) {
Может лучше поменять сигнатуру на привычную
```suggestion
    func setImage(with url: String) {
```
Кажется, что так будет достаточно просто использовать ее извне

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +    private var isAnimateRunning = false
Согласно грамматике это должно быть либо `isAnimationRunning`, либо `isAnimating`

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +                self?.image = errorImage
Давай добавим в эту функцию параметр `failurePlaceholder`, который по умолчанию равен `nil`, но если его передали, то будет отображаться он, а не дефолтная картинка с ошибкой?

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +    }
Эта функция будто бы нигде не вызывается 🤔

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +        gradientLayer.frame = bounds
Это бы лучше вынести в метод `layoutSubviews`

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +    }
Эта функция будто бы нигде не вызывается 🤔

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +        gradientLayer.frame = bounds
Это бы лучше вынести в метод `layoutSubviews`

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +        layer.addSublayer(gradientLayer)
А это в инит и в методах запуска/остановки анимации управлять видимостью этого слоя с помощью `isHidden`

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Services/ImageService.swift
> +    func loadWithUrl(_ url: String, _ completion: @escaping (Result<UIImage, HTTPError>) -> Void) -> Cancellable?
Если написать так, то будет выглядеть более свифтово. Ну и дописывать что конкретно мы пытаемся загрузить тоже хорошо
```suggestion
    func fetchImage(with url: String, completion: @escaping (Result<UIImage, HTTPError>) -> Void) -> Cancellable?
```

2021-12-15 08:17 UTC, Antowkos commented on DotaStats/Services/ImageService.swift
> +    }()
Кажется, что это можно сократить до 
```suggestion
    private let urlSession: URLSession = .init(configuration: URLSessionConfiguration.default)
```

2021-12-15 09:53 UTC, Antowkos reviewed
У меня не подтянулись изменения в `CachedImageView`, проверь, пжлст, что все запушилось

2021-12-15 09:53 UTC, Antowkos commented on DotaStats/Services/ImageService.swift
> +    func fetchImage(with url: String, _ completion: @escaping (Result<UIImage, HTTPError>) -> Void) -> Cancellable? {
Давай все-таки `completion` называть для внешнего потребителя

2021-12-15 09:58 UTC, straivi commented on DotaStats/Common/CachedImageView/CachedImageView.swift
> +    }
исправил, теперь вызывается в ините

2021-12-15 11:05 UTC, Antowkos approved these changes

2021-12-15 11:14 UTC, merged